import _Ascendant from "./Ascendant_avatar.png";
import _Assassin from "./Assassin_avatar.png";
import _Berserker from "./Berserker_avatar.png";
import _Champion from "./Champion_avatar.png";
import _Chieftain from "./Chieftain_avatar.png";
import _Deadeye from "./Deadeye_avatar.png";
import _Elementalist from "./Elementalist_avatar.png";
import _Gladiator from "./Gladiator_avatar.png";
import _Hierophant from "./Hierophant_avatar.png";
import _Inquisitor from "./Inquisitor_avatar.png";
import _Juggernaut from "./Juggernaut_avatar.png";
import _Necromancer from "./Necromancer_avatar.png";
import _Occultist from "./Occultist_avatar.png";
import _Pathfinder from "./Pathfinder_avatar.png";
import _Raider from "./Raider_avatar.png";
import _Saboteur from "./Saboteur_avatar.png";
import _Slayer from "./Slayer_avatar.png";
import _Trickster from "./Trickster_avatar.png";
import _Guardian from "./Guardian_avatar.png";

export const Ascendant = _Ascendant;
export const Assassin = _Assassin;
export const Berserker = _Berserker;
export const Champion = _Champion;
export const Chieftain = _Chieftain;
export const Deadeye = _Deadeye;
export const Elementalist = _Elementalist;
export const Gladiator = _Gladiator;
export const Hierophant = _Hierophant;
export const Inquisitor = _Inquisitor;
export const Juggernaut = _Juggernaut;
export const Necromancer = _Necromancer;
export const Occultist = _Occultist;
export const Pathfinder = _Pathfinder;
export const Raider = _Raider;
export const Saboteur = _Saboteur;
export const Slayer = _Slayer;
export const Trickster = _Trickster;
export const Guardian = _Guardian;

export { default as Marauder } from "./Marauder_avatar.png";
export { default as Duelist } from "./Duelist_avatar.png";
export { default as Ranger } from "./Ranger_avatar.png";
export { default as Shadow } from "./Shadow_avatar.png";
export { default as Witch } from "./Witch_avatar.png";
export { default as Templar } from "./Templar_avatar.png";
export { default as Scion } from "./Scion_avatar.png";
