// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RCB.JavaScript.Models;
using RCB.JavaScript.Models.Utils;

namespace RCB.JavaScript.Migrations
{
    [DbContext(typeof(PoeDbContext))]
    [Migration("20200801203419_CharacterCountAnalysis")]
    partial class CharacterCountAnalysis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RCB.JavaScript.Models.PoeCharacterModel", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("text");

                    b.Property<PoeAccount>("Account")
                        .HasColumnType("jsonb");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<CountAnalysis>("CountAnalysis")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Dead")
                        .HasColumnType("boolean");

                    b.Property<PoeDepth>("Depth")
                        .HasColumnType("jsonb");

                    b.Property<long>("EnergyShield")
                        .HasColumnType("bigint");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<List<PoeItem>>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("LifeUnreserved")
                        .HasColumnType("bigint");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<PathOfBuilding>("Pob")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PobCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15001);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("CountAnalysis")
                        .HasAnnotation("Npgsql:IndexMethod", "gin");

                    b.HasIndex("Items")
                        .HasAnnotation("Npgsql:IndexMethod", "gin");

                    b.HasIndex("Pob")
                        .HasAnnotation("Npgsql:IndexMethod", "gin");

                    b.HasIndex("CharacterName", "AccountName")
                        .IsUnique();

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
